# numpy概述

numpy（Numerical Python）提供了python对多维数组对象的支持：ndarray，具有矢量运算能力，快速、节省空间。numpy支持高级大量的维度数组与矩阵运算，此外也针对数组运算提供大量的数学函数库。

# 数组创建

In [25]:
#根据数值创建数组
import numpy as np
a = np.array([1, 2, 3, 4]) #列表方式
b = np.array((5, 6, 7, 8)) #元祖方式
c = np.array([[1,2,3],[2,3,4]]) #多维数组
d = np.array([1,2,3],dtype=np.float) #设定数组元素类型为int/float

In [26]:
#快速创建数组
import numpy as np
a=np.zeros((4,3)) #0数组
b=np.ones((4,3)) #1数组
c=np.arange(12) #默认从0开始到11的数组
d=np.arange(10,20) #元素为10到19的数组
e=np.arange(10,20,2) #元素为10到19,间隔为2的数组
f=np.arange(12).reshape((3,4))
g=np.linspace(1,10,50) #生成1到10，均匀分成5段的数列(默认50段）

In [7]:
# 创建随机数组
import numpy as np
# randn：np.random.randn(d0,d1,d2……dn) 返回一个或一组服从标准正态分布的随机样本值
a = np.random.randn(2,4)

# rand: np.random.rand(d0,d1,d2……dn)  返回一个或一组服从“0~1”均匀分布的随机样本值
b = np.random.rand(2,4) 

# random：np.random.random(size) 返回随机的浮点数，在半开区间 [0.0, 1.0),size为2个元素的列表时，返回二维数组
c = np.random.random(4) #随机的数组（0到1之间，不包括1）

# randint：numpy.random.randint(low, high=None, size=None, dtype=’l’) #返回随机整数或整型数组，范围区间为[low,high），包含low，不包含high；high没有填写时，默认生成随机数的范围是[0，low）
d = np.random.randint(1) 

# uniform：numpy.random.uniform(low,high,size)从一个均匀分布[low,high)中随机采样，注意定义域是左闭右开,size为2个元素的列表时，返回二维数组
e = np.random.uniform(0,1,10)

array([[ 0.38236443,  0.80607297,  0.31303243,  0.30638863,  0.17955938,
         0.55446301,  0.24505056,  0.64499654,  0.77934218,  0.08770291],
       [ 0.58526361,  0.64666954,  0.42587605,  0.30729551,  0.57435521,
         0.19592272,  0.71556856,  0.86258205,  0.0230364 ,  0.48001744]])

# 数组属性

In [28]:
import numpy as np
a = np.array([[1,2,3],[2,3,4]])
print('维度：',a.ndim) #返回数组维度
print('形状：',a.shape) #数组形状
print('元素个数',a.size) #元素个数
print('数据类型',a.dtype) #元素类型

维度： 2
形状： (2, 3)
元素个数 6
数据类型 int32


# 数组计算

In [29]:
#加、减、乘、除、平方、点乘、判断
import numpy as np
a = np.array([10,20,30,40])
b = np.arange(4)
c = a+b #对应元素相加、减、乘、除
d = a*b #对应元素相加、减、乘、除
e = b**2 #每个元素的平方
f = np.dot(a,b)#点乘，矩阵的运算
g = b<3 #对每个元素做判断，返回每个元素的true和false值
g

array([ True,  True,  True, False], dtype=bool)

# 数组操作

## 最大、最小、求和、平均值、索引

In [30]:
import numpy as np
a = np.array([[1,2,3],[7,8,9]])
b = np.sum(a) #总和,可指定axis=1或0，按照行/列计算
c = np.min(a) #最小值,可指定axis=1或0，按照行/列计算
d = np.max(a) #最大值,可指定axis=1或0，按照行/列计算
e = np.argmin(a) #最小值的索引，可指定axis=1或0，按照行/列计算
f = np.argmax(a) #最大值的索引，可指定axis=1或0，按照行/列计算
g = np.mean(a) #平均值，可指定axis=1或0，按照行/列计算

## 排序、转置、展平、格式转换

In [2]:
import numpy as np
a = np.array([[1,3,2],[7,9,8]])
np.sort(a) #排序
np.transpose(a) #转置
a.T #转置
a.flatten() #展平
b=a.astype(np.float64)
b.dtype

array([[1, 2, 3],
       [7, 8, 9]])

array([[1, 7],
       [3, 9],
       [2, 8]])

array([[1, 7],
       [3, 9],
       [2, 8]])

array([1, 3, 2, 7, 9, 8])

dtype('float64')

## 合并

In [32]:
import numpy as np
a = np.array([1,1,1])
b = np.array([2,2,2])
c = np.vstack((a,b)) #纵向合并
d = np.hstack((a,b)) #横向合并

## 过滤

In [38]:
#可以使用一个numpy数组作为索引数组去过滤原数组,索引数组里为true的值,保留,为false的值去掉
import numpy as np
a = np.arange(12).reshape((3,4))
b = a<3
c = a[b]
b
c

array([[ True,  True,  True, False],
       [False, False, False, False],
       [False, False, False, False]], dtype=bool)

array([0, 1, 2])

# 数组复制

In [34]:
#浅复制，两个数据一起变动
a=np.array([0,1,2,3])
b=a
a[0]=6
a #[6 1 2 3]
b #[6 1 2 3] 改变a,b也跟着改变
b[1]=10
b #[ 6 10  2  3]
a #[ 6 10  2  3]改变b,a也跟着改变

array([6, 1, 2, 3])

array([6, 1, 2, 3])

array([ 6, 10,  2,  3])

array([ 6, 10,  2,  3])

In [35]:
#深复制，两个数据互相独立
a=np.array([0,1,2,3])
b=a.copy()
a[0]=6
a #[6 1 2 3]
b #[0 1 2 3] 改变a,b不跟着改变
b[1]=10
b #[ 0 10  2  3]
a #[ 6 1  2  3]改变b,a不跟着改变，互相独立

array([6, 1, 2, 3])

array([0, 1, 2, 3])

array([ 0, 10,  2,  3])

array([6, 1, 2, 3])